### PR TITLE
Align (all) infix operators (if break)

### PR DESCRIPTION
**Pull request by hhugo**
Fix https://github.com/ocaml-ppx/ocamlformat/issues/69.

I personally find the code more readable this way. Feedback welcome.

### CODE REVIEW

**Comment by jberdine** [comment]
Motivated by this, I implemented the argument grouping heuristic used for general applications also for infix op arguments, see https://github.com/ocaml-ppx/ocamlformat/commit/cf82be1837727e37dc08f6887ea8ee00976efc4c. That change gives an intermediate between the previous behavior and the "always break" behavior of this PR. Can I ask you to try https://github.com/ocaml-ppx/ocamlformat/commit/cf82be1837727e37dc08f6887ea8ee00976efc4c and see if you still think the always break approach is needed?

**Comment by hhugo** [comment]
I had a look and I still prefer breaking always. I find (1) much easier to read.
Should we add a config ?

(1)
```
let sum_of_squares num =
  num + 1
  |> List.range 0
  |> List.map ~f:square
  |> List.fold_left ~init:0 ~f:( + )
```
(2)
```
let sum_of_squares num =
  num + 1 |> List.range 0 |> List.map ~f:square
  |> List.fold_left ~init:0 ~f:( + )
```

**Comment by jberdine** [comment]
Ok, yes, lets add an option. Independently, I wonder if `|>` is something of a special case, or at least wonder if there are two classes of infix ops: those that are primarily about control flow and those that are primarily about value computation. My impression is that for e.g. arithmetic, there is much less desire to always break. Thoughts?

**Comment by hhugo** [comment]
I'm not happy the option name, any suggestion ?

I had the same impression initially but I didn't manage to identify these two classes.

**Comment by jberdine** [comment]
For the name, perhaps `--break-infix=wrap` or `--break-infix=single-line-or-vertical` or perhaps `fit` instead of `single-line`?

**Pull request merged**
