### PR TITLE
Fix record break

### LINKED ISSUE #683: Weird line break before delimiter
```
echo "let xxxxxxxxxxxxxxxxxxxxxx x = { xxxxxxxxxxxxxx; xxxxxxxxxxxxxxxxxx = x; xxxxxxxxxxxxx }" | ~/l/ocamlformat/_build/dev/src/ocamlformat.exe --name a.ml --profile=janestreet -m  58 -
let xxxxxxxxxxxxxxxxxxxxxx x =
  { xxxxxxxxxxxxxx; xxxxxxxxxxxxxxxxxx = x; xxxxxxxxxxxxx
  }
;;
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #683

### CODE REVIEW

**Comment by gpetiot** [comment]
Is this one ready to go?

**Comment by hhugo** [comment]
```
$ echo "   type t = Enforce_style_config.Ocamlformat.t =
 { exceptions__ : String.Set.t [@default String.Set.empty] [@sexp_drop_if Set.is_empty] }" |  ~/l/ocamlformat/_build/dev/src/ocamlformat.exe --profile janestreet --name a.ml -
type t = Enforce_style_config.Ocamlformat.t =
  { exceptions__ : String.Set.t [@default String.Set.empty] [@sexp_drop_if Set.is_empty]
  }
```

**Comment by hhugo** [comment]
There are still some issue

**Comment by gpetiot** [comment]
> ```
> $ echo "   type t = Enforce_style_config.Ocamlformat.t =
>  { exceptions__ : String.Set.t [@default String.Set.empty] [@sexp_drop_if Set.is_empty] }" |  ~/l/ocamlformat/_build/dev/src/ocamlformat.exe --profile janestreet --name a.ml -
> type t = Enforce_style_config.Ocamlformat.t =
>   { exceptions__ : String.Set.t [@default String.Set.empty] [@sexp_drop_if Set.is_empty]
>   }
> ```

How would you like this one to be formatted instead?

**Comment by jberdine** [comment]
Note that this fixes a much wider-ranging bug in breaking of record expressions using `with`. Thanks!

**Comment by hhugo** [comment]
I would expect to get

```ocaml
type t = Enforce_style_config.Ocamlformat.t =
  { exceptions__ : String.Set.t
     [@default String.Set.empty]
     [@sexp_drop_if Set.is_empty]
  }
```

This is related to https://github.com/ocaml-ppx/ocamlformat/issues/706

**Pull request merged**
