### PR TITLE
Parse comments as docstrings if they contain odoc constructs

### PR DESCRIPTION
**Pull request by gpetiot**
This was suggested in the last message of #1165 (but it is not relevant to the first part of the issue)

The approach is to check if a comment contains odoc constructs (and not only checks if it can be formatted as a docstring, since regular comments can), if so: format it as a docstring.
The code is a bit ugly as we already have a dependency from Fmt_odoc to Cmt so we can't have one in the other direction (and it's not clear what code should be moved where).

### CODE REVIEW

**Comment by emillon** [comment]
I think we need to discuss a bit where we want to go with plain comments. In general, we can't say much about them since there are so many different ways to use them.

Independently of the correctness of this PR, maybe the right direction is the other one, ie never touch these comments?

**Comment by Julow** [comment]
About the dependencies, `Cmt` shouldn't contain formatting functions and `Fmt_odoc` shouldn't depend on `Cmt`. The fix for the second is simple, `Fmt_odoc.diff` shouldn't be here but in `Translation_unit` instead (it should be factored with `Cmt.diff`, leaving a more meaningful function in `Cmt` too).

**Comment by gpetiot** [comment]
Probably replaced by #1352

**Comment by gpetiot** [comment]
This approach does not fix the issue reported by Carl in #1165 by the way, it does not make it worse either but it would have to be reverted to fix #1165 anyway so I'm closing it.

**Pull request closed without merging**
