### PR TITLE
Fix invalid fragment delimiters of format-invalid-files recovery mode

### PR DESCRIPTION
**Pull request by hhugo**
- do not use double quoted string to store invalid source as it would emit invalid source in the presence of double quotes.
- simplify the logic wrapping invalid source with extension point.

### CODE REVIEW

**Comment by hhugo** [comment]
I'm not sure where to open this PR (here or in parse-wyc)

**Comment by gpetiot** [comment]
It's the right place for this PR, as I archived the parse-wyc repo. By the way I tried to find a testcase that exhibit the bug on master and would be fixed by this PR but I couldn't find one, do you have one?

**Comment by hhugo** [comment]
You just need to have double quote inside an invalid code fragment.
`let x = "123" + ` should do it I think

**Review by gpetiot — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
