### PR TITLE
Preserve comment indentation

### PR DESCRIPTION
**Pull request by Julow**
Closes https://github.com/ocaml-ppx/ocamlformat/issues/1132

Instead of stripping all indentation, only remove the indentation common to all the lines of the comment.

I intentionally add a regression: remove trailing empty lines. This add no diffs with `test_branch`, what do you think ?

### CODE REVIEW

**Comment by gpetiot** [comment]
Can you add a test similar to the usecase of Carl with different indentations for different lines?

**Comment by Julow** [comment]
Good idea. Done.

Should I keep removing the empty lines at the end of comments ?

**Comment by gpetiot** [comment]
> Should I keep removing the empty lines at the end of comments ?

It sounds reasonable to me

**Comment by gpetiot** [comment]
Can we merge this one?
Don't hesitate if you have feedback on this @ceastlund

**Comment by ceastlund** [comment]
Looks good to me.

**Pull request merged**
