### PR TITLE
Use `bos` instead of `stdio` for file operations

### PR DESCRIPTION
**Pull request by gpetiot**
More precise handling of errors, maybe could still be simplified with a cleaner propagation of errors.

### CODE REVIEW

**Comment by jberdine** [comment]
Why prefer bos over stdio?

**Comment by gpetiot** [comment]
I think the interface of `bos` is more adequate as it interfaces directly with `Fpath` that we already use, I also like the handling of errors better (most of them are currently ignored in this PR, for now, but we should propagate these errors with the errors we already handle, we need to work more on integrating this part of the code with the result type, but it could be done in a later PR).

**Comment by emillon** [comment]
independently of the actual changes, I think this kind of PR should get discussed a bit in advance.

**Comment by gpetiot** [comment]
Closing this one for now as we are not sure to make this change.

**Pull request closed without merging**
