### PR TITLE
Add spacing around = in records

### LINKED ISSUE #4: Record literal syntax--asymmetrical spacing around '='
# Observed behaviour

The following:

```ocaml
let x = {a = 1; b = true}
```

is reformatted as:

```ocaml
let x = {a= 1; b= true}
```

# Expected behaviour

One space on either side of the equals sign.

### PR DESCRIPTION
**Pull request by hcarty**
Fixes #4

### CODE REVIEW

**Comment by jberdine** [comment]
Considering the discussion in #4 , for this to proceed this change should be guarded behind an option in Conf.

**Comment by hcarty** [comment]
@jberdine What do you think of using the additional spacing when the sparse configuration option is `true`?  See the latest commit on this PR for a potential implementation.

If you're ok with this approach I can rebase so the PR can merge cleanly.

**Comment by hcarty** [comment]
And @yawaramin, same question.

**Comment by jberdine** [comment]
Technically, that would still not pass `make test`. :-) But more thoughtfully, I don't think that it is clear what sets of alternatives people will gravitate to. My instinct is that, if the implementation is separate, it would be better to have a separate option so that everyone can select the set of choices that work for them. Over time, some patterns may emerge, and those can be encoded into 'styles' that aggregate a number of finer-grained options. Does that make sense? But admittedly the name of `sparse` is currently pretty bad, sorry about that.

**Comment by hcarty** [comment]
Yeah, no tests added/checked/corrected yet :-)

I'll think on this a bit more.  The appropriate configuration option may have something to do with whitespace padding around lots of syntactic elements, ex `{x= 1}` vs `{ x = 1 }`.

**Comment by jberdine** [comment]
Also, infer uses the sparse config, and `make test` checks that it doesn't change the formatting of infer and ocamlformat itself. :-)

**Comment by yawaramin** [comment]
IMHO, configurable styles defeat the purpose of a code formatter. I am happy with one, consistent, style.

**Comment by hcarty** [comment]
Thanks for the reviews!  I'll close this for now. If/when I come up with something more complete and separate I'll submit an updated PR.

I agree that, ideally, there will be one format used for projects. Even if that format evolves over time. That said, having some configurable options available helps when figuring out what that format should be! So there's some value in this early stage of the project in having more configuration options than most projects would or should use.

**Comment by jberdine** [comment]
I agree that there would be value in all OCaml projects adopting the same style. But realistically that is very very far away. And more importantly, I think that there is a lot of value in auto-formatting a project even if the style is not exactly the same as some other projects. I think we can realize this second value long before the entire community agrees on a single style. And I agree that we need alternatives to evaluate the alternatives.

**Comment by yawaramin** [comment]
Yes, agree that a young project needs some options to help judge between different styles. IMO a style configuration file (a 'style file') would be better than adding a bunch of command-line flags to the ocamlformat tool. This way in the future you don't need to break compatibility with previous versions if you want to remove options. You can just ship a standard style file and let that be the default for everyone who is OK with following the default style.

Btw, I'm not asserting that all OCaml projects should follow the same style, just that ocamlformat should try really hard to enforce a single consistent style. I think style files would allow a happy middle ground.

**Comment by jberdine** [comment]
Currently there are both command line options and a config file, although there has been little consideration for accepting config files of previous versions. That's a good point. Or are you saying that it would be better to have only the file?

**Comment by yawaramin** [comment]
Exactly, it would be best to allow configuration with only a style file. This way you don't need to worry about adding or removing command-line flags, you have one command-line flag (e.g., `--style`) and you make the tool forward-compatible by ignoring style file configuration it doesn't understand, and backward-compatible by supporting configuration of previous versions. Best of both worlds.

**Pull request closed without merging**
