### PR TITLE
Fix travis script checking the changelog

### PR DESCRIPTION
**Pull request by Julow**
It isn't working since a few weeks. This PR is to debug it.

### CODE REVIEW

**Comment by gpetiot** [comment]
I feel like the time debugging this script over and over again is not worth it, now we all have the habit to update the CHANGES.md file for each PR, maybe it's time to remove this check?

**Comment by Julow** [comment]
I debugged and found two problems:
- `$TRAVIS_COMMIT` don't point to a valid commit sometimes, fixed.
- Github rate limiting prevent checking for the label, this was silently skipping the check. Now it's doing the changelog check anyway.

I agree the time to debug this script is not well spent.
I don't agree with your second point, I'm not used to it and will probably fail to update the changelog if we remove it. We should keep it.

**Comment by emillon** [comment]
Yeah, we had the same kind of problem on dune.

**Comment by Julow** [comment]
To summarize, with this PR the changelog check will be performed if we hit rate limit (eg. this PR) instead of silently not checking.
I think this is fine because most PRs requires changes and I prefer to explicitly ignore a red CI sometimes than not trusting it.

**Comment by Julow** [comment]
Here is what would happen:

| | Before | This PR |
|---|---|---|
| no label, no changelog | fails only sometimes | failure |
| no label, changelog entry | success | success |
| label, _ | success | fails sometimes |

**Comment by gpetiot** [comment]
Alright then you can merge if it's ready.

**Pull request merged**
