### PR TITLE
Fix weird space before type with ocp-indent-compat

### PR DESCRIPTION
**Pull request by gpetiot**
From https://github.com/janestreet/ocamlformat/commit/d6241cfd3fa32c486689e1d1666e277ef674c03d

### CODE REVIEW

**Comment by hhugo** [comment]
This only make sense if ocp-indent is applied after ocamlformat. This might be a good time to add a test for that include ocp-indent.

**Comment by hhugo** [comment]
@Julow, I don't understand why you want a new option here ?

**Comment by Julow** [comment]
Using `ocp-indent-compat` seems arbitrary and some people may want to have the `->` before, without the initial padding (I do).

**Comment by gpetiot** [comment]
One of those it-works-locally-but-not-on-the-CI bugs.

**Comment by Julow** [comment]
I think it's because you must pass `--with-test` to `opam install` in `.travis.yaml` in the `install` rule.

**Comment by gpetiot** [comment]
Not necessary anymore since #694 has been merged

**Pull request closed without merging**
