### PR TITLE
Expose let_binding_deindent_fun flag

### PR DESCRIPTION
**Pull request by henrytill**
Currently, for any non-`janestreet` profile, lines beginning with the `fun` keyword are de-indented:
```ocaml
let foo a b c d : int -> int -> int -> int -> int =
 fun e f g h -> a + b + c + d + e + f + g + h
```
For the `janestreet` profile, these lines are indented normally: 
```ocaml
let foo a b c d : int -> int -> int -> int -> int =
  fun e f g h -> a + b + c + d + e + f + g + h
```

This PR exposes the internal setting to enable this de-indent behavior as a configuration flag.

closes ocaml-ppx/ocamlformat#2491

### CODE REVIEW

**Review by Julow — APPROVED** [review]
I'm in favor of this change. This option is unlikely to go away and doesn't interact with other complex parts.

**Comment by Julow** [comment]
You need to update the generated manpage with `dune build @gen_manpage --auto-promote`. Also, could you add a changelog ?

**Comment by henrytill** [comment]
> You need to update the generated manpage with `dune build @gen_manpage --auto-promote`. Also, could you add a changelog ?

Updated manpage and changelog.

**Review by gpetiot — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
