### PR TITLE
Improve position of semisemi tokens

### LINKED ISSUE #1389: Bug: double semicolons formatting
I feel formatting double semicolons is strange.
I don't know whether it is bug or not.

**How to Reproduce**

version
```
% ocamlformat --version
0.14.2
```

src.ml
```
print_string "hoge";;
print_string "fuga"
```

command
```
% ocamlformat --profile=ocamlformat src.ml
;;
print_string "hoge"

;;
print_string "fuga"
```

I don't know why the first double semicolons appear at the first line. Is it bug?

+ `.ocamlformat` doesn't exist.
+ I tried all profiles (conventional, compact, sparse, ocamlformat, janestreet), but all were the same result.

`--print-config` result
```
% ocamlformat --profile=ocamlformat --print-config
profile=ocamlformat (command line)
quiet=false (profile ocamlformat (command line))
max-iters=10 (profile ocamlformat (command line))
comment-check=true (profile ocamlformat (command line))
wrap-fun-args=true (profile ocamlformat (command line))
wrap-comments=false (profile ocamlformat (command line))
type-decl-indent=2 (profile ocamlformat (command line))
type-decl=compact (profile ocamlformat (command line))
stritem-extension-indent=0 (profile ocamlformat (command line))
space-around-variants=false (profile ocamlformat (command line))
space-around-records=false (profile ocamlformat (command line))
space-around-lists=false (profile ocamlformat (command line))
space-around-arrays=false (profile ocamlformat (command line))
single-case=compact (profile ocamlformat (command line))
sequence-style=separator (profile ocamlformat (command line))
sequence-blank-line=compact (profile ocamlformat (command line))
parse-docstrings=false (profile ocamlformat (command line))
parens-tuple-patterns=multi-line-only (profile ocamlformat (command line))
parens-tuple=always (profile ocamlformat (command line))
parens-ite=false (profile ocamlformat (command line))
ocp-indent-compat=false (profile ocamlformat (command line))
nested-match=wrap (profile ocamlformat (command line))
module-item-spacing=sparse (profile ocamlformat (command line))
max-indent=68 (profile ocamlformat (command line))
match-indent-nested=never (profile ocamlformat (command line))
match-indent=0 (profile ocamlformat (command line))
margin=80 (profile ocamlformat (command line))
let-open=preserve (profile ocamlformat (command line))
let-module=compact (profile ocamlformat (command line))
let-binding-spacing=compact (profile ocamlformat (command line))
let-binding-indent=2 (profile ocamlformat (command line))
let-and=compact (profile ocamlformat (command line))
leading-nested-match-parens=false (profile ocamlformat (command line))
infix-precedence=indent (profile ocamlformat (command line))
indicate-nested-or-patterns=space (profile ocamlformat (command line))
indicate-multiline-delimiters=space (profile ocamlformat (command line))
indent-after-in=0 (profile ocamlformat (command line))
if-then-else=compact (profile ocamlformat (command line))
function-indent-nested=never (profile ocamlformat (command line))
function-indent=2 (profile ocamlformat (command line))
field-space=tight (profile ocamlformat (command line))
extension-sugar=preserve (profile ocamlformat (command line))
extension-indent=2 (profile ocamlformat (command line))
exp-grouping=parens (profile ocamlformat (command line))
escape-strings=preserve (profile ocamlformat (command line))
escape-chars=preserve (profile ocamlformat (command line))
dock-collection-brackets=false (profile ocamlformat (command line))
doc-comments-tag-only=default (profile ocamlformat (command line))
doc-comments-padding=2 (profile ocamlformat (command line))
doc-comments-val=unset (profile ocamlformat (command line))
doc-comments=before-except-val (profile ocamlformat (command line))
disambiguate-non-breaking-match=false (profile ocamlformat (command line))
disable=false (profile ocamlformat (command line))
cases-matching-exp-indent=compact (profile ocamlformat (command line))
cases-exp-indent=4 (profile ocamlformat (command line))
break-struct=force (profile ocamlformat (command line))
break-string-literals=auto (profile ocamlformat (command line))
break-sequences=false (profile ocamlformat (command line))
break-separators=before (profile ocamlformat (command line))
break-infix-before-func=true (profile ocamlformat (command line))
break-infix=wrap (profile ocamlformat (command line))
break-fun-sig=wrap (profile ocamlformat (command line))
break-fun-decl=wrap (profile ocamlformat (command line))
break-collection-expressions=fit-or-vertical (profile ocamlformat (command line))
break-cases=nested (profile ocamlformat (command line))
break-before-in=fit-or-vertical (profile ocamlformat (command line))
assignment-operator=end-line (profile ocamlformat (command line))
align-variants-decl=false (profile ocamlformat (command line))
align-constructors-decl=false (profile ocamlformat (command line))
align-cases=false (profile ocamlformat (command line))
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1389

The diff of test_branch.sh looks as good as the diff of js_source.ml

### CODE REVIEW

**Comment by gpetiot** [comment]
Since it's a big change, cc @ceastlund for the impact on janestreet's codebase, @jberdine for the impact on facebook's codebase, @CraigFe @samoht for mirage/irmin, even though I doubt someone will miss having the `;;` at the beginning of items.

**Comment by ceastlund** [comment]
So what's the new rule? Double-semicolons in toplevel context are added at the end of forms, but only when needed (i.e. when the next form is an expression)? They seem to be left off in other places, whereas in ordinary .ml files we add them to all multi-line forms, even when not syntactically necessary.

**Comment by gpetiot** [comment]
The new rule is:
- put `;;` after the current item/directive if it is followed by an expression evaluation
- put `;;` after the current item (not a directive) if it is followed by a directive

**Comment by ceastlund** [comment]
I think this will be fine inside Jane Street.

**Comment by hhugo** [comment]
The previous formatting had been chosen carefully to increase locality of top-level expressions and ease copy-pasting and commenting. For example, consider the following example.
```ocaml
let x = 2
(* Let's
 put here
 a big
 comment
 explaining
 why 2 is 
 a good
 number *)

;;
print_int x
```

With the double semicolon right before the expression, it's easy to copy-paste or comment/uncomment the top-level expression.
The new style, while used by most people, would require additional manual typing.

Also note that adding/removing a toplevel expression can affect the formatting many lines above the change.

I'm writing all theses mostly to give more context.

**Comment by jberdine** [comment]
Yes, the reasoning is what hhugo said. Placing the `;;` after the preceding item makes sense in the JS style where all/most structure items have trailing `;;` anyhow, but in other styles it does not make much sense.

I'll have to see what we can do about this one. At least this reverts cleanly so I can do that for the moment.

**Comment by samoht** [comment]
@gpetiot I'm not sure we are using `;;` at all in the irmin/mirage codebase.

**Pull request merged**
