### PR TITLE
Remove extra space before documentation in record declarations

### PR DESCRIPTION
**Pull request by Julow**
This is one of https://github.com/ocaml-ppx/ocamlformat/issues/569. There is 2 spaces just before documentation comments in:

```ocaml
type t =
  { x : int  (** comment *)
  ; y : int  (** comment for y *)
  }
```

This space may be there on purpose, should I add an option to put it back?

EDIT:
Now this PR is about adding the `doc_comments_padding` option
It's `2` by default and `1` in the Janestreet profile

### CODE REVIEW

**Comment by hhugo** [comment]
@jberdine, can you explain the reasoning behind these double spaces?

**Comment by Julow** [comment]
We could add a case to the `doc-comments` option, e.g `After_padded`

**Comment by jberdine** [comment]
The reasoning for two spaces isn't deep, just based on feedback to the effect that the docstrings end up crowding the code itself. This is more apparent when the docstrings are not vertically aligned with each other, as then they are generally quite visually distinct.

An additional case for doc-comments could work, but might be confusing since the docstrings for e.g. record fields are always placed after.

But however it is configured this is not specific to records, the spacing should be the same for e.g. docstrings on constructors.

**Comment by hhugo** [comment]
@mbarbin, do you have strong opinions on this ?

**Comment by Julow** [comment]
I updated this PR for variant and extension constructors and polymorphic variant and object types.
An option like `doc_comments_padding=2` would make sense ?

**Comment by gpetiot** [comment]
> I updated this PR for variant and extension constructors and polymorphic variant and object types.
> An option like `doc_comments_padding=2` would make sense ?

It makes sense to have this option if we can't agree on the appropriate number of spaces.

**Comment by Julow** [comment]
I added the `doc-comments-padding` option. @jberdine I set `1` as the default, do you prefer we keep `2` ?

**Comment by jberdine** [comment]
Yes, in general: keep defaults of new options to current behavior for at least one release.

**Comment by Julow** [comment]
I set the default back to `2` but keep `1` in the Janestreet profile.

**Comment by jberdine** [comment]
Could you rebase and resolve conflicts so I can test?

**Comment by Julow** [comment]
Rebased and cleaned.

**Comment by gpetiot** [comment]
You can test with tools/test_branch.sh that it doesn't break anything, but otherwise looks good.

**Pull request merged**
