### PR TITLE
Fix position of comments following a record field

### LINKED ISSUE #1944: Bug: how to keep comments of in the right of each field of a record type?
Hi,

**Describe the bug**

It seems that OCamlformat always puts the right-side comments of a record type's fields into the next line.

Can anyone advise me on how to prevent it from breaking right-side comments into new lines?

**How to Reproduce**

For example, here is my original code (`foo.ml`):

```ocaml
(* file name: foo.ml *)
type program =
  { prog_globals : global list;       (* global variables *)
    prog_struct_types : lltype list;  (* data structures *)
    prog_lib_funcs : func list;       (* library functions *)
    prog_init_funcs : func list;      (* initialization functions *)
    prog_user_funcs : func list;      (* functions from user code *)
    prog_entry_funcs : func list;     (* main/entry functions *)
  }
```

After running `ocamlformat foo.ml`, I obtain the following output (which is undesired, since all the comments are placed in newlines)

``` ocaml
type program =
  { prog_globals : global list;
    (* global variables *)
    prog_struct_types : lltype list;
    (* data structures *)
    prog_lib_funcs : func list;
    (* library functions *)
    prog_init_funcs : func list;
    (* initialization functions *)
    prog_user_funcs : func list;
    (* functions from user code *)
    prog_entry_funcs : func list (* main/entry functions *)
  }
```

- Here is the content of my configuration file:

  ```
  profile = janestreet

  # Generals
  margin = 79
  ocp-indent-compat=true
  break-before-in = auto

  break-sequences = false
  break-string-literals = never
  single-case = compact
  break-separators = after

  # Documentation and comments
  wrap-comments = false
  comment-check = false
  sequence-blank-line = preserve-one                     # allow blank lines
  exp-grouping = preserve

  # Use wrap infix to avoid breaking string concatenation (^) into many lines
  break-infix = wrap
  wrap-fun-args = true
  break-fun-sig = wrap
  type-decl = sparse
  ```

  and the result of `--print-config`

  ```
  ocamlformat --print-config
  profile=janestreet (file ../.ocamlformat:9)
  quiet=false (profile janestreet (file ../.ocamlformat:9))
  max-iters=10 (profile janestreet (file ../.ocamlformat:9))
  comment-check=false (file ../.ocamlformat:24)
  wrap-fun-args=true (file ../.ocamlformat:30)
  wrap-comments=false (file ../.ocamlformat:23)
  type-decl-indent=2 (profile janestreet (file ../.ocamlformat:9))
  type-decl=sparse (file ../.ocamlformat:32)
  stritem-extension-indent=0 (profile janestreet (file ../.ocamlformat:9))
  space-around-variants=true (profile janestreet (file ../.ocamlformat:9))
  space-around-records=true (profile janestreet (file ../.ocamlformat:9))
  space-around-lists=true (profile janestreet (file ../.ocamlformat:9))
  space-around-arrays=true (profile janestreet (file ../.ocamlformat:9))
  single-case=compact (file ../.ocamlformat:19)
  sequence-style=terminator (profile janestreet (file ../.ocamlformat:9))
  sequence-blank-line=preserve-one (file ../.ocamlformat:25)
  parse-docstrings=false (profile janestreet (file ../.ocamlformat:9))
  parens-tuple-patterns=multi-line-only (profile janestreet (file ../.ocamlformat:9))
  parens-tuple=multi-line-only (profile janestreet (file ../.ocamlformat:9))
  parens-ite=true (profile janestreet (file ../.ocamlformat:9))
  ocp-indent-compat=true (file ../.ocamlformat:14)
  nested-match=wrap (profile janestreet (file ../.ocamlformat:9))
  module-item-spacing=compact (profile janestreet (file ../.ocamlformat:9))
  max-indent=68 (profile janestreet (file ../.ocamlformat:9))
  match-indent-nested=never (profile janestreet (file ../.ocamlformat:9))
  match-indent=0 (profile janestreet (file ../.ocamlformat:9))
  margin=79 (file ../.ocamlformat:13)
  line-endings=lf (profile janestreet (file ../.ocamlformat:9))
  let-module=sparse (profile janestreet (file ../.ocamlformat:9))
  let-binding-spacing=double-semicolon (profile janestreet (file ../.ocamlformat:9))
  let-binding-indent=2 (profile janestreet (file ../.ocamlformat:9))
  let-and=sparse (profile janestreet (file ../.ocamlformat:9))
  leading-nested-match-parens=true (profile janestreet (file ../.ocamlformat:9))
  infix-precedence=parens (profile janestreet (file ../.ocamlformat:9))
  indicate-nested-or-patterns=unsafe-no (profile janestreet (file ../.ocamlformat:9))
  indicate-multiline-delimiters=no (profile janestreet (file ../.ocamlformat:9))
  indent-after-in=0 (profile janestreet (file ../.ocamlformat:9))
  if-then-else=keyword-first (profile janestreet (file ../.ocamlformat:9))
  function-indent-nested=never (profile janestreet (file ../.ocamlformat:9))
  function-indent=2 (profile janestreet (file ../.ocamlformat:9))
  field-space=loose (profile janestreet (file ../.ocamlformat:9))
  extension-indent=2 (profile janestreet (file ../.ocamlformat:9))
  exp-grouping=preserve (file ../.ocamlformat:26)
  dock-collection-brackets=false (profile janestreet (file ../.ocamlformat:9))
  doc-comments-tag-only=fit (profile janestreet (file ../.ocamlformat:9))
  doc-comments-padding=1 (profile janestreet (file ../.ocamlformat:9))
  doc-comments=before (profile janestreet (file ../.ocamlformat:9))
  disambiguate-non-breaking-match=false (profile janestreet (file ../.ocamlformat:9))
  disable=false (profile janestreet (file ../.ocamlformat:9))
  cases-matching-exp-indent=normal (profile janestreet (file ../.ocamlformat:9))
  cases-exp-indent=2 (profile janestreet (file ../.ocamlformat:9))
  break-struct=force (profile janestreet (file ../.ocamlformat:9))
  break-string-literals=never (file ../.ocamlformat:18)
  break-sequences=false (file ../.ocamlformat:17)
  break-separators=after (file ../.ocamlformat:20)
  break-infix-before-func=true (profile janestreet (file ../.ocamlformat:9))
  break-infix=wrap (file ../.ocamlformat:29)
  break-fun-sig=wrap (file ../.ocamlformat:31)
  break-fun-decl=fit-or-vertical (profile janestreet (file ../.ocamlformat:9))
  break-collection-expressions=fit-or-vertical (profile janestreet (file ../.ocamlformat:9))
  break-cases=fit-or-vertical (profile janestreet (file ../.ocamlformat:9))
  break-before-in=auto (file ../.ocamlformat:15)
  assignment-operator=begin-line (profile janestreet (file ../.ocamlformat:9))
  align-variants-decl=false (profile janestreet (file ../.ocamlformat:9))
  align-constructors-decl=false (profile janestreet (file ../.ocamlformat:9))
  align-cases=false (profile janestreet (file ../.ocamlformat:9))
  ```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1944

Here is test_branch's diff for `ocamlformat` profile (no diff for default and janestreet):
```diff
diff --git a/middle_end/flambda/simple_value_approx.mli b/middle_end/flambda/simple_value_approx.mli
index 29ee305e9..e829427de 100644
--- a/middle_end/flambda/simple_value_approx.mli
+++ b/middle_end/flambda/simple_value_approx.mli
@@ -26,8 +26,7 @@ type 'a boxed_int =
   | Nativeint : nativeint boxed_int
 
 type value_string =
-  {contents: string option; (* [None] if unknown or mutable *)
-                            size: int}
+  {contents: string option (* [None] if unknown or mutable *); size: int}
 
 type unresolved_value =
   | Set_of_closures_id of Set_of_closures_id.t
diff --git a/otherlibs/unix/unix.ml b/otherlibs/unix/unix.ml
index 3499b011d..d71868fc8 100644
--- a/otherlibs/unix/unix.ml
+++ b/otherlibs/unix/unix.ml
@@ -571,8 +571,7 @@ external utimes : string -> float -> float -> unit = "unix_utimes"
 
 type interval_timer = ITIMER_REAL | ITIMER_VIRTUAL | ITIMER_PROF
 
-type interval_timer_status = {it_interval: float; (* Period *)
-                                                  it_value: float}
+type interval_timer_status = {it_interval: float (* Period *); it_value: float}
 (* Current value of the timer *)

 external getitimer : interval_timer -> interval_timer_status = "unix_getitimer"
```

### CODE REVIEW

**Review by Julow — COMMENTED** [review]
This doesn't work with for the original issue, where the SEMI token is placed at the end of the line. With the options `--profile=janestreet --break-separator=after`.

It doesn't look nice also when the comments are already on their own line with ocamlformat's profile:
```ocaml
type program =       
  { prog_globals: global list
  ; (* global variables *)
    prog_struct_types: lltype list
  ; (* data structures *)
    prog_lib_funcs: func list
  ; (* library functions *)
    prog_init_funcs: func list
  ; (* initialization functions *)
    prog_user_funcs: func list
  ; (* functions from user code *)
    prog_entry_funcs: func list (* main/entry functions *) }
```

**Comment by gpetiot** [comment]
With the example from #1944 and `--profile jane break-separators after` I get:
```ocaml
type program =
  { prog_globals : global list; (* global variables *)
    prog_struct_types : lltype list; (* data structures *)
    prog_lib_funcs : func list; (* library functions *)
    prog_init_funcs : func list; (* initialization functions *)
    prog_user_funcs : func list; (* functions from user code *)
    prog_entry_funcs : func list (* main/entry functions *)
  }
```
Comments are now attached to the previous element.

On the other hand, comments after `;` at the beginning of the line (like your example), the comments are still being attached to the next element like it used to be. That's what is already one and I think it makes sense to keep it this way.

**Comment by taquangtrung** [comment]
@gpetiot: thank you for the quick update! I just tested on the branch https://github.com/gpetiot/ocamlformat/tree/fix-cmts-after-semicolon and confirm that I obtained the same result:

```ocaml
type program =
  { prog_globals : global list; (* global variables *)
    prog_struct_types : lltype list; (* data structures *)
    prog_lib_funcs : func list; (* library functions *)
    prog_init_funcs : func list; (* initialization functions *)
    prog_user_funcs : func list; (* functions from user code *)
    prog_entry_funcs : func list (* main/entry functions *)
  }
```

**Comment by Julow** [comment]
The comments should all be attached to their previous item in this example:
```ocaml
type program =
  { prog_globals : global list;
    (* global variables *)
    prog_struct_types : lltype list;
    (* data structures *)
    prog_lib_funcs : func list;
    (* library functions *)
    prog_init_funcs : func list;
    (* initialization functions *)
    prog_user_funcs : func list;
    (* functions from user code *)
    prog_entry_funcs : func list (* main/entry functions *)
  }
```

(especially since this is the output corresponding to the example from the issue)
This now formats to this with `--profile=default --break-separator=before`:
```ocaml
type program = {     
    prog_globals : global list
  ; (* global variables *)
    prog_struct_types : lltype list
  ; (* data structures *)
    prog_lib_funcs : func list
  ; (* library functions *)
    prog_init_funcs : func list
  ; (* initialization functions *)
    prog_user_funcs : func list
  ; (* functions from user code *)
    prog_entry_funcs : func list (* main/entry functions *)
}
```

**Comment by gpetiot** [comment]
Yes but this code is not produced by ocamlformat anymore (with this patch). So as an input supposedly written by the user it doesn't shock me to consider the comments to be attached to the next element, users that want the comments to be attached to the previous field either have to move it at the end of the previous line, or align it vertically but on the preceding line of the corresponding field.

**Comment by taquangtrung** [comment]
@Julow: oh, is it the case that you ran `ocamlformat` a different input file where the comments were already separated on new lines?

Here are my results on 2 runs:

1. Run `ocamlformat --profile janestreet --break-separator after` on the original input file `foo.ml`

   Input `foo1.ml`:

   ```ocaml
   type program =
     { prog_globals : global list;        (* global variables *)
       prog_struct_types : lltype list;   (* data structures *)
       prog_lib_funcs : func list;        (* library functions *)
       prog_init_funcs : func list;       (* initialization functions *)
       prog_user_funcs : func list;       (* functions from user code *)
       prog_entry_funcs : func list;      (* main/entry functions *)
     }
   ```

   Output:

   ```ocaml
   type program =
     { prog_globals : global list; (* global variables *)
       prog_struct_types : lltype list; (* data structures *)
       prog_lib_funcs : func list; (* library functions *)
       prog_init_funcs : func list; (* initialization functions *)
       prog_user_funcs : func list; (* functions from user code *)
       prog_entry_funcs : func list (* main/entry functions *)
     }
   ```

2. Run `ocamlformat --profile janestreet --break-separator after`  on the other output `foo2.ml`:

   Input `foo2.ml`:

   ```ocaml
   type program =
    { prog_globals : global list;
      (* global variables *)
      prog_struct_types : lltype list;
      (* data structures *)
      prog_lib_funcs : func list;
      (* library functions *)
      prog_init_funcs : func list;
      (* initialization functions *)
      prog_user_funcs : func list;
      (* functions from user code *)
      prog_entry_funcs : func list (* main/entry functions *)
    }
   ```

   Output:

   ```ocaml
   type program =
    { prog_globals : global list;
      (* global variables *)
      prog_struct_types : lltype list;
      (* data structures *)
      prog_lib_funcs : func list;
      (* library functions *)
      prog_init_funcs : func list;
      (* initialization functions *)
      prog_user_funcs : func list;
      (* functions from user code *)
      prog_entry_funcs : func list (* main/entry functions *)
    }
   ```

**Review by Julow — APPROVED** [review]
@taquangtrung Yes, I ran ocamlformat with inputs that are only vaguely related to the issue. I was trying to challenge the patch, sorry if that wasn't clear.

@gpetiot You are right, that's the same comment placement as before. It is unexpected to me though, it is different than for doc-comments. That's an other issue for later.

**Pull request merged**
