### PR TITLE
[WIP] [JS] Improve: various whitespaces

### PR DESCRIPTION
**Pull request by gpetiot**
From the JS fork.

### CODE REVIEW

**Comment by hhugo** [comment]
It would be better to split the change, from the reformatting

**Comment by hhugo** [comment]
Also, I suspect that this will need to go under an option

**Comment by hhugo** [comment]
Also, I suspect that this will need to go under an option

**Comment by hhugo** [comment]
You might even need to split it in multiple pr, depending on how many changes are included in that commit

**Comment by gpetiot** [comment]
I don't know if it is a good thing to split it, it may impact many files but the changes are not that big.
Of course we can add an option, although I like this new style better (would like to make it the new default).

**Comment by jberdine** [comment]
Yes, agree, but even more, it would be better to add the options and then perhaps change the settings with the resulting format change in a separate PR.

**Comment by gpetiot** [comment]
Alright, I will split this PR and add new options.

**Pull request closed without merging**
