### PR TITLE
Fix placement of comments on constants

### PR DESCRIPTION
**Pull request by gpetiot**
Related to #1323 but insufficient to fix it somehow. No diff with test_branch.

### CODE REVIEW

**Comment by gpetiot** [comment]
I'm waiting a bit before merging it, as #1387 can make it obsolete (having the loc in the ast instead of inferring them)

**Comment by hhugo** [comment]
Note that the loc in the ast will only be valid with ocaml >= 4.10.

**Comment by hhugo** [comment]
I wonder if we should lex the full source once when calling Source.create instead of lexing bits and pieces multiple times..

**Comment by emillon** [comment]
FYI, in the read/format/output part, the profile is about:

- parsing: 13%
- comment handling (Cmts.init): 33%
- formatting + box layout: 46%

And calls to `Source` functions that reparse the file are barely visible.

**Comment by jberdine** [comment]
Interesting, thanks @emillon! The interval tree data structure was a quick and slow implementation, and it shows. Regarding the effect that queries to `Source` have though, I think that the story is more involved. In particular, since we have to keep reformatting in a loop until a fixed point is reached, the cost of a use of Source is not immediately clear. In particular, if it can lead to another entire iteration (or more) of the format-parse loop, then the cost is much higher than what raw `perf` data would indicate. It is this sort of cost that I am more worried about, rather than the efficiency of the token parsing itself, which is not free but also not bad. Basically, the uses of Source are the point where we introduce backtracking that `Format` does not natively support, which is what takes the algorithm from polynomial time (`Format`) to exponential time (like pretty and friends).

**Pull request merged**
