### PR TITLE
Do not normalize newlines inside quoted strings

### LINKED ISSUE #1748: Bug: trailing carriage returns removed from string literals
**Describe the bug**
ocamlformat removes trailing carriage returns from delimited string literals.  I think this might be related to the recent change to CRLF-handling behavior, but it seems like ocamlformat should never touch string literals in a way that would change the actual contents of the string.

**How to Reproduce**

Below is an example file.  Please replace `^M` with actual carriage return characters.

```ocaml
let%expect_test _ =
  do_test (fun () ->
    let%bind () = system "cat foo.csv" in
    [%expect
      {|
    e,d,f^M
    "x
    x",x,xxx^M
    e,d,f
    "x
    x",x,xxx^M
    yy,y,"y
    yy"
   |}];
    return ())
;;
```

When ocamlformat is run on the above file, the carriage returns disappera.

Options:
```
--profile=janestreet
--enable-outside-detected-project
```

### PR DESCRIPTION
**Pull request by nojb**
This is an alternative instead of #1753 to solve the problem in #1748, suggested by @hhugo: we simply avoid touching the newlines inside quoted strings `{|...|}`.

The implementation is simple (also suggested by @hhugo): after the final AST has been produced we iterate once over it, recording the locations of such strings, sorted by character position. Later, when normalizing the newlines according to the setting of `line-endings`, we skip those newlines that fall inside one of the locations recorded previously.

Fixes #1748

### CODE REVIEW

**Comment by hhugo** [comment]
I took the liberty to rewrite your patch a bit.
- It should now handle the string pattern case (`Ppat_constant ..`).
- The fact that strings are untouched is more explicit.
- `\r\r\r\r\n` now gets normalized as `\n' in `Lf` mode and `\r\n` in `Crlf` mode. Consecutive Cr were previously kept

**Comment by nojb** [comment]
> I took the liberty to rewrite your patch a bit.
> 
> * It should now handle the string pattern case (`Ppat_constant ..`).
> * The fact that strings are untouched is more explicit.
> * `\r\r\r\r\n` now gets normalized as `\n' in `Lf`mode and`\r\n`in`Crlf` mode. Consecutive Cr were previously kept

Looks good, thanks! I'm closing #1753 in favour of this one.

**Comment by hhugo** [comment]
@nojb, can you rebase the pr and fix the conflict.
@jberdine , how do you like this approach ?
@ceastlund, does this work for you ?

**Comment by nojb** [comment]
> @nojb, can you rebase the pr and fix the conflict.

Done.

**Comment by nojb** [comment]
Friendly ping

**Comment by gpetiot** [comment]
The implementation looks good to me, thanks!

@bcc32 does this change fix the bug you repoprted?

**Comment by bcc32** [comment]
@nojb @gpetiot Yes, this patch seems to work!  Thank you!

**Review by gpetiot — APPROVED** [review]
Alright looks good then!

**Comment by nojb** [comment]
Thanks!

**Comment by jberdine** [comment]
> @jberdine , how do you like this approach ?

This seems ok to me. But this has all made me wonder whether this is actually simpler than https://github.com/ocaml-ppx/ocamlformat/pull/274 ? To me it seems much cleaner to override the formatter's output function to do translation when needed.

I also think that all defaults, not just the jane profile, should default to not changing string literals. Potentially semantics-changing behavior should need to be explicitly asked for, I think.

**Comment by nojb** [comment]
> I also think that all defaults, not just the jane profile, should default to not changing string literals. Potentially semantics-changing behavior should need to be explicitly asked for, I think.

Unlike the aborted #1753, this PR applies across the board: all users get the new (better) behaviour where newlines inside `{|...|}` are left untouched.

> But this has all made me wonder whether this is actually simpler than #274 ? To me it seems much cleaner to override the formatter's output function to do translation when needed.

Reviving #274 is the first thing I did #1703, but if I remember well there was a problem with newlines in verbatim blocks in docstrings not being correctly normalized, so I took the present approach (post-processing). But perhaps the original approach (overriding `out_newline`) can be made to work with a little more effort, not sure.

**Comment by jberdine** [comment]
> > I also think that all defaults, not just the jane profile, should default to not changing string literals. Potentially semantics-changing behavior should need to be explicitly asked for, I think.
> 
> Unlike the aborted #1753, this PR applies across the board: all users get the new (better) behaviour where newlines inside `{|...|}` are left untouched.

Thanks, my confusion between the two then.

> > But this has all made me wonder whether this is actually simpler than #274 ? To me it seems much cleaner to override the formatter's output function to do translation when needed.
> 
> Reviving #274 is the first thing I did #1703, but if I remember well there was a problem with newlines in verbatim blocks in docstrings not being correctly normalized, so I took the present approach (post-processing). But perhaps the original approach (overriding `out_newline`) can be made to work with a little more effort, not sure.

Ok, thanks for pointing out that issue. Do you know if that was the only one? I'm not sure how the implementation complexity of the two approaches would end up comparing, but it could be preferable to override `out_newline` and then explicitly transform strings (such as the bodies of verbatim blocks) that contain embedded newlines that should be normalized, rather than postprocessing all newlines except those explicitly collected in the preprocessing scan. The override approach would be a lighter touch, and I expect it would be clearer since the code would identify where action is taken rather than acting on everything except specially identified points. It would perhaps be slightly more efficient, though I don't know if it is significant.

**Comment by nojb** [comment]
We may want to revisit this issue following ocaml/ocaml#12514.

**Pull request merged**
