### PR TITLE
Improve: parens around not expressions

### PR DESCRIPTION
**Pull request by gpetiot**
From https://github.com/janestreet/ocamlformat/commit/7fcd0e265d584ce43abbfc0c2ab3ebb4240afc6f

### CODE REVIEW

**Comment by gpetiot** [comment]
Is this one ready to go?

**Comment by hhugo** [comment]
I'm not sure about this one. This was previously discussed in https://github.com/ocaml-ppx/ocamlformat/issues/266. The special case for "not" is kind of weird.
I would wait for feedback from @jberdine

**Comment by Julow** [comment]
I'm not fan of the new option `parens-not`. What do you think of adding a value to `infix-precedence`, eg. `parens-disambiguate`, which could be used to add other special cases ? Or to change the option name to be more general and extensible in the future ?

**Comment by gpetiot** [comment]
From #266 it looks like the current implementation does a good job, @hhugo do you have concrete examples that motivated you to write the original patch in the first place?

**Comment by hhugo** [comment]
Some people were unhappy about it. @mbarbin, any opinion on this ?

**Comment by mbarbin** [comment]
I am looking at jane with master without this PR, and I can't find bad examples at the moment.  I think this is OK to close this PR and we can re-open if we find a compelling example to add to the comment.  I think the rule to parenthesize not expressions seems good on master, we can plan on using it for 0.10 and see whether we get some complementary feedback on it for a future version of ocamlformat.

**Pull request closed without merging**
