### PR TITLE
Improve: new option to control spacing around let bindings

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
I think I misunderstood the reason for this. If people want to keep this behavor, we should probably encode it in using the `--module-item-spacing` option.

**Comment by jberdine** [comment]
Or it could be modified slightly to add your `;;` after multi-line let-bindings.

**Comment by hhugo** [comment]
Not really happy with names and documentation

**Comment by hhugo** [comment]
waiting for https://github.com/ocaml-ppx/ocamlformat/pull/367 to be merged.

**Comment by hhugo** [comment]
Rebased.
Regarding merging the option with module-item-spacing, I think there are a bit orthogonal. Janestreet would use module-item-spacing=compact with let-binding-spacing=double-semicolon

**Pull request merged**
