### PR TITLE
Add missing parenthesis around constrained pattern in class

### LINKED ISSUE #1729: BUG: ast changed
0.19.0 with default options
```ocaml
class virtual accumulate_flows =
  let (mc_exit : _) =
    match nb_trajectories_ratio with
    | _ when errs ->
        invalid_arg ""
  in
  object
  end
```

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #1729, no diff with test_branch.sh

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Looks good.

Is there a `Ppat_constraint` that isn't parenthesed in other contexts ?

**Comment by Julow** [comment]
> Is there a Ppat_constraint that isn't parenthesed in other contexts ?

Of course, there's the pattern of a `let` or a letop. It is already handled above, however, so this can be simplified into 
```ocaml
    | _, Ppat_constraint _ -> true
```
eg. add parentheses by default for `Ppat_constraint`. I think this pattern tends to have parentheses more often than not.

**Comment by gpetiot** [comment]
I factorized these cases, there was no diff with test_branch.sh, and updated the changelog

**Review by Julow — APPROVED** [review]
LGTM

**Comment by nojb** [comment]
Thanks!

**Pull request merged**
