### PR TITLE
Restore previous functionality for pre-post extension points

### PR DESCRIPTION
**Pull request by jberdine**
plus a test case

### CODE REVIEW

**Comment by jberdine** [comment]
Any feedback on this one? It is one we need to upgrade.

**Comment by jberdine** [comment]
Any feedback on this one?

**Comment by jberdine** [comment]
Don't worry, it was hard to decipher that code and there wasn't a test originally.

**Comment by gpetiot** [comment]
I rebased it but something is wrong, it includes #1196 even though it is already merged (starting from a fresh and clean repository didn't help). Does somebody have an idea?

**Comment by jberdine** [comment]
Re the 0.14.2 tag, it is on a commit not an ancestor of master without the pr number. I guess the tag should be moved to the commit f0f9606, I guess created by the github ui.

**Pull request merged**
