### PR TITLE
JaneStreet profile: improve indentation of function body when max-indent is used

### LINKED ISSUE #2201: Feature request: improved `fun` formatting in janestreet profile
In some cases, contents of multi-line `fun` expressions are indented too little or too far.

These two cases have the `fun` bodies indented no further than the surrounding code, which is misleading:

```
let x =
  some_fun________________________________
    some_arg______________________________
    (fun param ->
    do_something ();
    do_something_else ();
    return_this_value)
;;
```

```
let x =
  some_fun________________________________
    some_arg______________________________
    ~f:(fun param ->
    do_something ();
    do_something_else ();
    return_this_value)
;;
```

These two cases have the `fun` bodies indented four or more spaces further than the surrounding code, rather than just two, which eats up more space than necessary:

```
let x =
  some_value
  |> some_fun (fun x ->
       do_something ();
       do_something_else ();
       return_this_value)
;;
```

```
let x =
  some_value
  ^ some_fun (fun x ->
      do_something ();
      do_something_else ();
      return_this_value)
;;
```

### PR DESCRIPTION
**Pull request by gpetiot**
This is an attempt to fix #2201

This works well for the `janestreet` profile, however for the `conventional` profile the indentation is not correct when `max-indent = 2` is set:
```ocaml
let x =                                
  some_fun________________________________
    some_arg______________________________ (fun param ->
    do_something ();
    do_something_else ();
    return_this_value)
```
But this is identical to what the main branch produces.

This could be a temporary patch to help janestreet upgrade their ocamlformat version while waiting to migrate from Format to Pprint.

Btw the commit adding a location to arg_labels could be extracted as a separate PR.

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Looks good to me.

I do not believe the `max-indent` option needs more in the `conventional` profile. It's too general to be maintained. I'd rather remove it and replace it with a new kind of internal options not settable by users.

**Comment by Julow** [comment]
Should we merge this ?

**Review by Julow — APPROVED** [review]
Merged main, the diff looks good. Ready to be merged!

**Review by donedealtraders — COMMENTED** [review]
### ###

**Pull request merged**
