### PR TITLE
Type identifiers can have a disambiguation suffix

### PR DESCRIPTION
**Pull request by gpetiot**
This change is made for https://github.com/ocaml/ocaml-lsp/pull/386

No diff with test_branch.sh

### CODE REVIEW

**Comment by hhugo** [comment]
How is that not breaking parsing ?
Can you add tests for things like `a/2` or even `a/2n`

**Comment by trefis** [comment]
To expand a bit on @hhugo's message: the lexer changes are going to have an impact in other contexts, not just for identifiers in type expressions.
So it's likely to break the parsing of arithmetic expressions.

As I see it, you want to handle `t/n` only when formatting type expressions coming from merlin. It would make sense to have a separate entry point, and a dedicated lexer (or entry point in the lexer), for those.
The parser changes seem fine as they are though.

**Comment by gpetiot** [comment]
I'm having a look at that, but the change is very involved.

**Comment by hhugo** [comment]
Not ideal but what about changing the parser to accept `LIDENT SLASH INT` in the right context instead ?

**Comment by voodoos** [comment]
> Not ideal but what about changing the parser to accept `LIDENT SLASH INT` in the right context instead ?

Yes, to only allow type idents to have slashes and not value idents. This would prevent the confusion with the arithmetic `/ `.

**Comment by trefis** [comment]
There is no `SLASH` token, you'd have to allow `LIDENT INFIXOP3 INT` in that context which is a bit more permissive than intended, but that doesn't really matter too much.
Not sure what the conflicts would look like though.

**Comment by trefis** [comment]
Looks like there are no conflicts:
```
--- a/parsing/parser.mly
+++ b/parsing/parser.mly
@@ -3600,13 +3600,25 @@ label_longident:
     mk_longident(mod_longident, LIDENT) { $1 }
 ;
 type_longident:
-    mk_longident(mod_ext_longident, LIDENT)  { $1 }
+    mk_longident(mod_ext_longident, disambiguated_lident)  { $1 }
+;
+disambiguated_lident:
+    LIDENT { $1 }
+  | LIDENT op=INFIXOP3 INT {
+    assert (op = "/");
+    $1 ^ op ^ fst $3 }
+;
+disambiguated_uident:
+    UIDENT { $1 }
+  | UIDENT op=INFIXOP3 INT {
+    assert (op = "/");
+    $1 ^ op ^ fst $3 }
 ;
 mod_longident:
     mk_longident(mod_longident, UIDENT)  { $1 }
 ;
 mod_ext_longident:
-    mk_longident(mod_ext_longident, UIDENT) { $1 }
+    mk_longident(mod_ext_longident, disambiguated_uident) { $1 }
   | mod_ext_longident LPAREN mod_ext_longident RPAREN
       { lapply ~loc:$sloc $1 $3 }
   | mod_ext_longident LPAREN error
```
```
# let x : t / 3 -> int = fun _ -> ();;
Error: Unbound type constructor t/3
# let x : M/1 . t / 3 -> int = fun _ -> ();;
Error: Unbound module M/1
# let x : t lor 3 -> int = fun _ -> ();;
Fatal error: exception File "parsing/parser.mly", line 3610, characters 4-10: Assertion failed
```
(I guess you'll want to raise `Syntaxerr` instead of asserting)

**Comment by gpetiot** [comment]
I tried this approach as well but there is an issue with `M/2.t/2` (this can also be produced by the disambigation right?) I think the dot is considered part of the INT and so it doesn't find the dot to be part of the module identifier.

**Comment by nojb** [comment]
Hello, I **think** this change breaks parsing of expressions of the form `(???)/2`

image

**Comment by gpetiot** [comment]
This change has been reverted to give us more time to work out a better solution. Sorry for the inconvenience!

**Pull request merged**
