### PR TITLE
Improve: fmt_module

### PR DESCRIPTION
**Pull request by gpetiot**
@Julow I feel like it's better to rework `fmt_module` (with a minimal diff in formatting, mainly improving the code) before working on #619 and other module-related issues.

### CODE REVIEW

**Comment by gpetiot** [comment]
I think the diff is already big enough and we can merge this one, I also think the indentation changes are an improvement, do you agree @jberdine @hhugo @Julow ?

**Comment by jberdine** [comment]
This causes many regressions with test_branch due to the indentation of modules not taking leading parens into account. An option could be added to ignore leading parens when determining the indentation, but it should be applied to other syntactic forms too.

**Comment by jberdine** [comment]
Is it expected that this will be quick to fix, or should we revert in order to make the 0.9 release?

**Comment by gpetiot** [comment]
We only have to revert this commit: 4377c44

**Pull request merged**
