### PR TITLE
Fix normalization of odoc paragraphs

### LINKED ISSUE #1686: Bug: "comments changed" | Cannot process a doc comment with a new line at the beginning
**Describe the bug**

ocamlformat 0.17.0 cannot process a doc comment with a new line at the beginning

**How to Reproduce**

`ocamlformat --impl -` and put this code:

```ocaml
(**

works?
*)
let a = 1
```

results in 

```
ocamlformat: Cannot process "<standard input>".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: comments changed.
```

`.ocamlformat`:

```
version=0.17.0
break-separators=before
dock-collection-brackets=false
break-sequences=true
doc-comments=before
field-space=loose
let-and=sparse
sequence-style=terminator
type-decl=sparse
wrap-comments=true
if-then-else=k-r
let-and=sparse
space-around-records
space-around-lists
space-around-arrays
cases-exp-indent=2
break-cases=all
indicate-nested-or-patterns=unsafe-no
parse-docstrings=true
```

The option `--print-config` prints the configuration on the standard output, please put the result of this command in the report if you are not sure which option causes the issue.

```
profile=default
quiet=false
max-iters=10
comment-check=true
wrap-fun-args=true
wrap-comments=true (file .ocamlformat:10)
type-decl-indent=2
type-decl=sparse (file .ocamlformat:9)
stritem-extension-indent=0
space-around-variants=true
space-around-records=true (file .ocamlformat:13)
space-around-lists=true (file .ocamlformat:14)
space-around-arrays=true (file .ocamlformat:15)
single-case=compact
sequence-style=terminator (file .ocamlformat:8)
sequence-blank-line=preserve-one
parse-docstrings=true (file .ocamlformat:19)
parens-tuple-patterns=multi-line-only
parens-tuple=always
parens-ite=false
ocp-indent-compat=false
nested-match=wrap
module-item-spacing=sparse
max-indent=68
match-indent-nested=never
match-indent=0
margin=80
let-module=compact
let-binding-spacing=compact
let-binding-indent=2
let-and=sparse (file .ocamlformat:12)
leading-nested-match-parens=false
infix-precedence=indent
indicate-nested-or-patterns=unsafe-no (file .ocamlformat:18)
indicate-multiline-delimiters=no
indent-after-in=0
if-then-else=k-r (file .ocamlformat:11)
function-indent-nested=never
function-indent=2
field-space=loose (file .ocamlformat:6)
extension-indent=2
exp-grouping=parens
dock-collection-brackets=false (file .ocamlformat:3)
doc-comments-tag-only=default
doc-comments-padding=2
doc-comments=before (file .ocamlformat:5)
disambiguate-non-breaking-match=false
disable=false
cases-matching-exp-indent=normal
cases-exp-indent=2 (file .ocamlformat:16)
break-struct=force
break-string-literals=auto
break-sequences=true (file .ocamlformat:4)
break-separators=before (file .ocamlformat:2)
break-infix-before-func=false
break-infix=wrap
break-fun-sig=wrap
break-fun-decl=wrap
break-collection-expressions=fit-or-vertical
break-cases=all (file .ocamlformat:17)
break-before-in=fit-or-vertical
assignment-operator=end-line
align-variants-decl=false
align-constructors-decl=false
align-cases=false
```

### PR DESCRIPTION
**Pull request by gpetiot**
I added a comment to keep trace of it, paragraphs must not be considered for the normalized form. They are only structural and the shape of a docstring organized in paragraphs only depend on linebreaks, which may be changed by the formatting.

I also changed the normalized output of other nodes, using `Node(X,Y)` instead of `Node,X,Y` as it is more convenient for debugging. No diff with test_branch.sh

Fix #1686

### CODE REVIEW

**Comment by hhugo** [comment]
I don't understand this change. I don't understand what structural mean in this context. Surely, we don't want ocamlformat to alter paragraph inside doc comment. The only test added here is about a blank leading blank line. What about other cases such that trailing newline or blank lines in the middle ?

**Comment by hhugo** [comment]
I don't understand this change. Surely, we don't want ocamlformat to alter paragraph inside doc comment. The only test added here is about a blank leading blank line. What about other cases such that trailing newline or blank lines in the middle of a comment ?

**Comment by gpetiot** [comment]
My assumption was that we didn't want to preserve these, but if that's an issue I will try to improve that before the release.

**Comment by hhugo** [comment]
We probably don't care about preserving leading blank lines. But preserving paragraph seems essential. Take a look at the document of any library from @dbuenzli.

**Comment by hhugo** [comment]
We probably don't care about preserving leading blank lines. But preserving paragraph seems essential. Take a look at the document of any library from @dbuenzli.

**Comment by gpetiot** [comment]
I'm adding more tests in #1706 and it looks like paragraphs are preserved, only the leading and trailing blank lines are removed.

**Comment by hhugo** [comment]
It's good that they are preserved, but are we still checking that ? What I understand from your change is that it's removing the check for paragraphs ..

**Comment by hhugo** [comment]
Any update regarding my last comment ?

**Comment by gpetiot** [comment]
Yes this change removed the check, I didn't have time to work on a different change that would keep this check but also fix #1636 since I'm trying to wrap up the 0.19.0 release. What I can do is revert this PR's change and work on a fix for 0.20.0.

**Comment by hhugo** [comment]
I would imagine that normalizing parsed doc comment to remove empty paragraph would be enough

**Comment by gpetiot** [comment]
I tried that but no that's not enough unfortunately.

**Pull request merged**
