### PR TITLE
Build: update to base v0.12

### PR DESCRIPTION
**Pull request by jberdine**

### CODE REVIEW

**Comment by Julow** [comment]
I'm getting compilation error:
I'm using OCaml `4.06.1` and Base `v0.12`

```
File "src/Cmts.ml", line 210, characters 12-22:
Warning 6: label equal was omitted in the application of this function.
File "src/Cmts.ml", line 210, characters 23-33:
Error: This expression has type 'a -> 'a -> bool
       but an expression was expected of type 'b list

File "src/Normalize.ml", line 406, characters 4-19:
Error: This variant pattern is expected to have type ('a * 'b) list option
       The constructor Unequal_lengths does not belong to type option

File "src/Conf.ml", line 1392, characters 21-33:
Error: This expression has type Import.String.t -> Import.String.t -> bool
       but an expression was expected of type 'a Import.List.t = 'a list

File "src/Conf.ml", line 1392, characters 10-20:
Warning 6: label equal was omitted in the application of this function.
File "src/Conf.ml", line 1392, characters 21-33:
Error: This expression has type string -> string -> bool
       but an expression was expected of type 'a list
```

**Comment by gpetiot** [comment]
Do you still have this issue? On master and with `base.v0.12.0` it should be fine.

**Comment by Julow** [comment]
It works on master, after a clean. I'm now getting parsing errors on `js_source.ml` and `source.ml` and some compilation errors:

```
File "src/Reason.ml", line 199, characters 4-8:
Error: The GADT constructor Impl of type Binary_reason.ast
       must be qualified in this pattern.
File "src/Reason.ml", line 199, characters 4-8:
Error: The GADT constructor Impl of type Binary_reason.ast
       must be qualified in this pattern.
```

I'm on OCaml 4.06.1 and this is my `opam list --required-by=ocamlformat` (after `opam install ./ocamlformat.opam`):

```
base                    v0.12.0     Full standard library replacement for OCaml
base-unix               base
cmdliner                1.0.3       Declarative definition of command line interfaces for OCaml
dune                    1.6.3       Fast, portable and opinionated build system
fpath                   0.7.2       File system paths for OCaml
jbuilder                transition  This is a transition package, jbuilder is now named dune. Use the dune
ocaml                   4.06.1      The OCaml compiler (virtual package)
ocaml-migrate-parsetree 1.2.0       Convert OCaml parsetrees between different versions
ocamlformat_support     --          Support package for OCamlFormat
octavius                1.2.0       Ocamldoc comment syntax parser
stdio                   v0.12.0     Standard IO library for OCaml
uutf                    1.0.1       Non-blocking streaming Unicode codec for OCaml
```

**Comment by gpetiot** [comment]
Maybe you could try with a more recent ocaml. Here is my config:
```
base                    v0.12.0     Full standard library replacement for OCaml
base-unix               base
cmdliner                1.0.3       Declarative definition of command line inter
dune                    1.7.3       Fast, portable and opinionated build system
fpath                   0.7.2       File system paths for OCaml
jbuilder                transition  This is a transition package, jbuilder is no
ocaml                   4.07.1      The OCaml compiler (virtual package)
ocaml-migrate-parsetree 1.2.0       Convert OCaml parsetrees between different v
ocamlformat_support     --          Support package for OCamlFormat
stdio                   v0.12.0     Standard IO library for OCaml
```

**Comment by gpetiot** [comment]
@jberdine is it ok to revert this commit, to release 0.9 with base v0.11, and do another minor release for base v0.12 ?

**Comment by jberdine** [comment]
Why? I don't know the motivation.

**Comment by hhugo** [comment]
https://github.com/ocaml-ppx/ocamlformat/pull/659

**Pull request merged**
