### PR TITLE
Improve compatibility with ocp-indent

### PR DESCRIPTION
**Pull request by Julow**
These are changes from https://github.com/ocaml-ppx/ocamlformat/pull/2314 that I extracted and polished a bit.

This is a work-in-progress, the goal is to cause no regressions on the default profile.

### CODE REVIEW

**Comment by Julow** [comment]
Ready for review. There's a regression that I would like to keep:

```diff
   | (* Cancellation requested. Build jobs are immediately rejected in this
        state *)
-    Restarting_build of
-      Memo.Invalidation.t
+    Restarting_build of Memo.Invalidation.t
```

The constructor decl used to break after the `of` due to the comment.

**Comment by Julow** [comment]
The constructor declaration change is moved to a different PR for easier blaming and better changelog: https://github.com/ocaml-ppx/ocamlformat/pull/2429

**Review by gpetiot — APPROVED** [review]
LGTM!

**Comment by Julow** [comment]
While looking at the diffs, I found 3 similar changes that I added here. I'll merge if test_branch reports no regression.

**Comment by Julow** [comment]
No diff in test_branch, merging!

**Pull request merged**
