### PR TITLE
Use dune subst instead of gen_version.sh

### LINKED ISSUE #470: gen_version.sh is not portable
Hi,

When `/bin/sh` is not bash, some errors are displayed:

```
          sh src/Version.ml [dev]
../tools/gen_version.sh: 7: ../tools/gen_version.sh: [[: not found
../tools/gen_version.sh: 12: ../tools/gen_version.sh: [[: not found
          sh src/Version.ml [release]
../tools/gen_version.sh: 7: ../tools/gen_version.sh: [[: not found
../tools/gen_version.sh: 12: ../tools/gen_version.sh: [[: not found
dune build _build/release/ocamlformat-help.txt
          sh src/Version.ml [release]
../tools/gen_version.sh: 7: ../tools/gen_version.sh: [[: not found
../tools/gen_version.sh: 12: ../tools/gen_version.sh: [[: not found
```

The reason is that it's invoked with `(sh)`, but this is a bash script. In particular, it uses `[[` to do pattern matching.

There are some ways to do that in a portable way using vanilla `sh`, but I'm wondering if there's a particular reason not to use `dune subst` for this?

Thanks

### PR DESCRIPTION
**Pull request by Julow**
Alternative to #664 (alternative to #471 (fix #470)).

`tools/gen_version.sh` is not needed and can be replaced by `dune subst`.

The problem with this approach is that for pinned or dev builds, the `"%%VERSION%%"` will be the commit hash.

### CODE REVIEW

**Comment by jberdine** [comment]
Thanks for writing this up. What I don't understand with this approach is how each build is tagged with the correct version. Have I misunderstood?

**Comment by Julow** [comment]
They are not, unless you run `subst`.

**Comment by jberdine** [comment]
I see, thanks. Ok, so we're still with #664.

**Comment by Julow** [comment]
Why is it important to tag local dev builds ?

**Comment by jberdine** [comment]
Depending on the work flow, exes built in this way end up being deployed elsewhere, and used to run tests. It is very easy to get confused about what test results correspond to what version if the exes have garbage versions internally. It would probably be ok if the correct version didn't get set until `dune install`, but until the next version of dune, I don't think that is possible.

**Comment by Julow** [comment]
I understand. Note that `opam install ./ocamlformat.opam` triggers the subst:
```
 > ocamlformat --version
6da8dfd
```

I close in favor of #664.

**Comment by jberdine** [comment]
Yes, but the overhead of `opam install` is much higher than that of `dune install`. Perhaps it is my failure to read the docs, but since opam2 it seems impossible to pin local packages without opam making a copy of the source dir. And even worse, if the project root isn't the git root, then it has to use rsync, which copies all the build artifacts. So e.g. in my normal setup a few dirs down from ocamlformat/test there are a couple 10s of GB of llvm binaries.

**Pull request closed without merging**
