### PR TITLE
Fix comments on record fields

### PR DESCRIPTION
**Pull request by Julow**
Fixes https://github.com/ocaml-ppx/ocamlformat/issues/623
Which is a bug from https://github.com/ocaml-ppx/ocamlformat/pull/580

### CODE REVIEW

**Comment by gpetiot** [comment]
You forgot to apply `make fmt`, besides that is it ready to be reviewed?

**Comment by Julow** [comment]
Sorry, fixed and yes.

**Comment by gpetiot** [comment]
test_branch exhibits a regression:
```ocaml
diff --git a/sledge/src/llair/typ.ml b/sledge/src/llair/typ.ml
index cffad84f2..a542e2c25 100644
--- a/sledge/src/llair/typ.ml
+++ b/sledge/src/llair/typ.ml
@@ -16,8 +16,11 @@ type t =
   | Tuple of {elts: t vector; packed: bool}
   | Struct of
       { name: string
-      ; elts: t vector (* possibly cyclic, name unique *)
-            [@compare.ignore] [@equal.ignore] [@sexp_drop_if fun _ -> true]
+      ; elts: t vector
+            [@compare.ignore]
+            [@equal.ignore]
+            [@sexp_drop_if fun _ -> true]
+            (* possibly cyclic, name unique *)
       ; packed: bool }
   | Opaque of {name: string}
 [@@deriving compare, equal, hash, sexp]
```

**Comment by gpetiot** [comment]
My commit 5ea4429 fixes this, test_branch is now 100% OK. Let me know if it looks alright to you and I will merge.

**Comment by Julow** [comment]
Good for me.

**Pull request merged**
