### PR TITLE
Fix non stabilizing comments after infix operators (STAR, PERCENT, HASHOP)

### LINKED ISSUE #1770: Bug: comment after infix operator fails to stabilize
**Describe the bug**
Formatting does not stabilize with a comment after an infix operator.  Possibly related to #1611.

**How to Reproduce**

Formatting this file does not stabilize after 10 iterations:

```ocaml
let _ =
  1 +
  ( fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
   / barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
   * bazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
   * (* convert from foos to bars blah blah blah blah blah blah blah blah *)
   of_int (-10_000)
 );;

```

Options

```
--profile=janestreet
--enable-outside-detected-project
--disable-conf-files
```

### PR DESCRIPTION
**Pull request by gpetiot**
fix #1770, no diff with test_bransh.sh

I only found the issue after `STAR` and `PERCENT` tokens, let me know if you find other instances of this bug @bcc32 @ceastlund so I can integrate them to this PR

### CODE REVIEW

**Review by Julow — COMMENTED** [review]
I find stability issue with `#` too.

**Comment by gpetiot** [comment]
> I find stability issue with `#` too.

Done!

**Review by Julow — APPROVED** [review]
Looks good :)

**Comment by RADIA57** [comment]
TLS port how much --
Media portal how much --

**Pull request merged**
